Metrics/LineLength:
  Max: 120

Documentation:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - db/**/*
  # allows big blocks of code, comment out run rubocop then uncomment 
  # if 'Block has too many lines' are the only fails
  ExcludedMethods:
    ['describe', 'it']

Metrics/MethodLength:
  Enabled: true
  Exclude:
    - db/**/*
