services:
    - postgresql

addons:
    postgresql: '9.6'

language: ruby

rvm:
 - 2.5.0

os: osx

before_script:
    - cp config/database.yml.travis config/database.yml

script:
  - bundle exec rspec
  - bundle exec rubocop
